name: CICD Database Dev to Prod

on:
  push:
    branches:
      - main

jobs:
  db_cicd:
  name: Database CI/CD
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 #  Check out ke repository yang kita gunakan

    - name: SSH Connect
      uses: appleboy/ssh-action@v1 # Ganti dengan path tujuan di server Anda
      with:
        host: ${ { secrets.SERVER_HOST } } #IP server
        username: ${ { secrets.SERVER_USER } } #User server
        password: ${ { secrets.SERVER_PASSWORD } } #Password server
        script: |
          echo "Berhasil Konek ke Server"
